---
# Secret for sensitive Fabric environment variables.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patchworks.fullname" . }}-fabric-secret
  namespace: {{ include "patchworks.fabric.namespace" . }}
  labels:
    {{- include "patchworks.labels" . | nindent 4 }}
{{- $data := include "patchworks.fabricSecretData" . | trim }}
{{- if $data }}
stringData:
  {{- $data | nindent 2 }}
{{- end }}
