{{- $root := . }}
{{- range $namespace, $_ := (include "patchworks.consumerNamespaces" . | fromJson).serviceAccounts }}
{{- with $root }}
{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "patchworks.serviceAccountName" . }}
  namespace: {{ $namespace }}
  labels:
    {{- include "patchworks.labels" . | nindent 4 }}
  annotations:
    {{- mergeOverwrite (deepCopy (.Values.serviceAccount.annotations | default (dict))) (dict "argocd.argoproj.io/sync-wave" "-30") | toYaml | nindent 4 }}
{{- with .Values.image.pullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
